databaseType = "PostgreSql"
id = "c5b5b3cf-5f61-4b50-9a39-864728f03ceb"
name = "flyway_ai_chat"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flywayDesktop]
enableMigrations = true
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.target1]
url = "jdbc:postgresql://localhost:5432/app_db"
schemas = [ "public" ]
