services:
  main_service:
    build:
      context: ./main_service
    container_name: main_service
    env_file:
      - ./main_service/.env
    depends_on:
      - postgres
      - redis
      - chromadb
    ports:
      - "3000:3000"
    restart: unless-stopped

  llmservice:
    build:
      context: ./llmservice
    container_name: llmservice
    env_file:
      - ./llmservice/.env
    depends_on:
      - redis
      - ollama
    ports:
      - "3100:3100"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      no_cache: true
    container_name: nginx
    ports:
      - "3001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - main_service
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - OLLAMA_NUM_PARALLEL=2
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama/models:/models
      - ./ollama/scripts/init-model.sh:/init-model.sh
    entrypoint: ["/bin/bash"]
    command: ["/init-model.sh"]
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb-data:/chromadb/data
    environment:
      - ANONYMIZED_TELEMETRY=false
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  ollama-data:
  chromadb-data:
  postgres-data:
  redis-data:
