CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.request_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source varchar(20) NOT NULL,
  duration_ms integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.queries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  request_log_id integer,
  response_id uuid,
  is_primary boolean NOT NULL DEFAULT false
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_queries_response_id'
  ) THEN
    ALTER TABLE public.queries
      ADD CONSTRAINT fk_queries_response_id
      FOREIGN KEY (response_id)
      REFERENCES public.responses(id)
      ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_queries_request_log_id'
  ) THEN
    ALTER TABLE public.queries
      ADD CONSTRAINT fk_queries_request_log_id
      FOREIGN KEY (request_log_id)
      REFERENCES public.request_logs(id);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_queries_request_log_id
  ON public.queries(request_log_id)
  WHERE request_log_id IS NOT NULL;
